version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: DockerFile
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}

  postgres:
    image: bitnami/postgresql:16
    container_name: postgres_bitnami
    restart: unless-stopped
    ports:
     - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
    driver: local
